/* Generated by configure */
#include <vulkan/vulkan.h>
// The pData parameter has changed from uint32_t* to void* at some point.
// Ensure the headers have the updated one to prevent compile errors later on.
PFN_vkCmdUpdateBuffer cmdUpdBuf;
void testUpdateBuffer(VkCommandBuffer commandBuffer, VkBuffer dstBuffer, VkDeviceSize dstOffset, VkDeviceSize dataSize, const void* pData)
{
    cmdUpdBuf(commandBuffer, dstBuffer, dstOffset, dataSize, pData);
}
int main(int argc, char **argv)
{
    (void)argc; (void)argv;
    /* BEGIN TEST: */
    VkInstanceCreateInfo info;
    testUpdateBuffer(0, 0, 0, 0, 0);
    /* END TEST */
    return 0;
}
