QT.multimedia.enabled_features = 
QT.multimedia.disabled_features = 
QT.multimedia.QT_CONFIG = alsa pulseaudio
QT.multimedia.exports = 
QT.multimedia_private.enabled_features = alsa gstreamer_1_0 gstreamer gstreamer_app gstreamer_encodingprofiles gstreamer_photography linux_v4l pulseaudio
QT.multimedia_private.disabled_features = directshow directshow-player evr gpu_vivante gstreamer_0_10 openal resourcepolicy wasapi wmf wmf-player wmsdk wshellitem
QT.multimedia_private.libraries = alsa gstreamer gstreamer_app gstreamer_photography pulseaudio
QMAKE_LIBS_ALSA = /usr/lib/x86_64-linux-gnu/libasound.so
QMAKE_LIBS_GSTREAMER = /usr/lib/x86_64-linux-gnu/libgstpbutils-1.0.so /usr/lib/x86_64-linux-gnu/libgstaudio-1.0.so /usr/lib/x86_64-linux-gnu/libgstvideo-1.0.so /usr/lib/x86_64-linux-gnu/libgstbase-1.0.so /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so /usr/lib/x86_64-linux-gnu/libgobject-2.0.so /usr/lib/x86_64-linux-gnu/libglib-2.0.so
QMAKE_INCDIR_GSTREAMER = /usr/include/gstreamer-1.0 /usr/include/orc-0.4 /usr/include/gstreamer-1.0 /usr/include/glib-2.0 /usr/lib/x86_64-linux-gnu/glib-2.0/include
QMAKE_LIBS_GSTREAMER_APP = /usr/lib/x86_64-linux-gnu/libgstapp-1.0.so
QMAKE_DEPENDS_GSTREAMER_APP_CC = GSTREAMER
QMAKE_DEPENDS_GSTREAMER_APP_LD = GSTREAMER
QMAKE_LIBS_GSTREAMER_PHOTOGRAPHY = /usr/lib/x86_64-linux-gnu/libgstphotography-1.0.so
QMAKE_DEPENDS_GSTREAMER_PHOTOGRAPHY_CC = GSTREAMER
QMAKE_DEPENDS_GSTREAMER_PHOTOGRAPHY_LD = GSTREAMER
QMAKE_LIBS_PULSEAUDIO = /usr/lib/x86_64-linux-gnu/libpulse-mainloop-glib.so /usr/lib/x86_64-linux-gnu/libpulse.so /usr/lib/x86_64-linux-gnu/libglib-2.0.so
QMAKE_DEFINES_PULSEAUDIO = _REENTRANT
QMAKE_INCDIR_PULSEAUDIO = /usr/include/glib-2.0 /usr/lib/x86_64-linux-gnu/glib-2.0/include
